---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pinniped-config-controller-manager
rules:
- resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- resources:
  - configmaps
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - secrets
  verbs:
  - get
  - list
  - watch
